"""add_widget_configs_table

Revision ID: 39a6d7f2e573
Revises: 42072dbb1524
Create Date: 2026-09-02 19:23:43.883759

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39a6d7f2e573'
down_revision: Union[str, Sequence[str], None] = '42072dbb1524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('site_key', sa.String(length=100), nullable=False),
    sa.Column('bot_title', sa.String(length=100), nullable=False),
    sa.Column('greeting_message', sa.Text(), nullable=False),
    sa.Column('primary_color', sa.String(length=20), nullable=False),
    sa.Column('allowed_domains', sa.Text(), nullable=True, comment='Comma-separated allowed domain origins e.g. example.com,app.example.com or * for all'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_widget_configs_company_id'), 'widget_configs', ['company_id'], unique=True)
    op.create_index(op.f('ix_widget_configs_site_key'), 'widget_configs', ['site_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_widget_configs_site_key'), table_name='widget_configs')
    op.drop_index(op.f('ix_widget_configs_company_id'), table_name='widget_configs')
    op.drop_table('widget_configs')
    # ### end Alembic commands ###
